### ISSUE TITLE
Continuing Comptibility Issues 

### ISSUE THREAD

**Issue by MQSchleich** [flairNLP/flair#1385]
The bug seems similar to flairNLP/flair#1359

```

from flair.data import Sentence
from flair.models import SequenceTagger

# make a sentence
sentence = Sentence('Es muss einen tieferen Grund geben.')

# load the NER tagger
tagger = SequenceTagger.load('de-pos-fine-grained')

# run NER over sentence
tagger.predict(sentence)```

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-f69c06402a7b> in <module>
      9 
     10 # run NER over sentence
---> 11 tagger.predict(sentence)
     12 

/usr/local/lib/python3.7/dist-packages/flair/models/sequence_tagger_model.py in predict(self, sentences, mini_batch_size, embedding_storage_mode, all_tag_prob, verbose, use_tokenizer)
    356                     continue
    357 
--> 358                 feature: torch.Tensor = self.forward(batch)
    359                 tags, all_tags = self._obtain_labels(
    360                     feature=feature,

/usr/local/lib/python3.7/dist-packages/flair/models/sequence_tagger_model.py in forward(self, sentences)
    496     def forward(self, sentences: List[Sentence]):
    497 
--> 498         self.embeddings.embed(sentences)
    499 
    500         lengths: List[int] = [len(sentence.tokens) for sentence in sentences]

/usr/local/lib/python3.7/dist-packages/flair/embeddings.py in embed(self, sentences, static_embeddings)
    175 
    176         for embedding in self.embeddings:
--> 177             embedding.embed(sentences)
    178 
    179     @property

/usr/local/lib/python3.7/dist-packages/flair/embeddings.py in embed(self, sentences)
     94 
     95         if not everything_embedded or not self.static_embeddings:
---> 96             self._add_embeddings_internal(sentences)
     97 
     98         return sentences

/usr/local/lib/python3.7/dist-packages/flair/embeddings.py in _add_embeddings_internal(self, sentences)
   2636         # get hidden states from language model
   2637         all_hidden_states_in_lm = self.lm.get_representation(
-> 2638             text_sentences, start_marker, end_marker, self.chars_per_chunk
   2639         )
   2640 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    574                 return modules[name]
    575         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 576             type(self).__name__, name))
    577 
    578     def __setattr__(self, name, value):

AttributeError: 'CharLMEmbeddings' object has no attribute 'chars_per_chunk'
```

- OS [e.g. iOS, Linux]: Ubuntu 19.10
- flair version: commit a1ef91a691a9f882fb0d0bd48d04b570f6b0079b

**Comment by djstrong** [comment]
I doubt it worked with previous version 0.4.4.
`self.chars_per_chunk` is uninitialized in: 
https://github.com/flairNLP/flair/blob/a1ef91a691a9f882fb0d0bd48d04b570f6b0079b/flair/embeddings.py#L2638

**Comment by djstrong** [comment]
Duplicate of https://github.com/flairNLP/flair/issues/1365
