### ISSUE TITLE
get error when run "from flair.models import SequenceTagger"

### ISSUE THREAD

**Issue by MohsinKamal23** [flairNLP/flair#1311]
A clear and concise description of what you want to know.
Hi 
when i run this line"from flair.models import SequenceTagger" following error occur " module 'flair' has no attribute 'nn' "

python version=3.7.3
flair version == 0.4.3
torch version == 1.1.0
![image](https://user-images.githubusercontent.com/40856743/70235996-de8b9400-1785-11ea-8624-257845cf0803.png)

**Comment by severinsimmler** [comment]
Since the latest Flair version is 0.4.4, try upgrading the library with

```
$ pip install --upgrade flair
```

**Comment by MohsinKamal23** [comment]
Thanks 
work fine in flair version == 0.4.4 and torch version == 1.2.0
