### ISSUE TITLE
[Question] Why I cannot perform training when the parameter  train_with_test = True?

### ISSUE THREAD

**Issue by afi1289** [flairNLP/flair#2106]
Hello,
I am trying to train a model for named-entity recognition, and I have two questions:
**First**: When I set the parameter `train_with_test = True` as follows: 
````
trainer_MOD.train('sequence-labeling/MOD',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=150,
              train_with_dev = False,
              train_with_test = True,
              embeddings_storage_mode = 'gpu')
````
I have the following error message:
````
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-7f344f8d6ab0> in <module>
      6               train_with_dev = False,
      7               train_with_test = False,
----> 8               embeddings_storage_mode = 'gpu') #https://github.com/flairNLP/flair/blob/master/flair/trainers/trainer.py

/opt/conda/lib/python3.7/site-packages/flair/trainers/trainer.py in train(self, base_path, learning_rate, mini_batch_size, mini_batch_chunk_size, max_epochs, scheduler, cycle_momentum, anneal_factor, patience, initial_extra_patience, min_learning_rate, train_with_dev, monitor_train, monitor_test, embeddings_storage_mode, checkpoint, save_final_model, anneal_with_restarts, anneal_with_prestarts, batch_growth_annealing, shuffle, param_selection_mode, write_weights, num_workers, sampler, use_amp, amp_opt_level, eval_on_train_fraction, eval_on_train_shuffle, save_model_at_each_epoch, **kwargs)
    224 
    225         optimizer: torch.optim.Optimizer = self.optimizer(
--> 226             self.model.parameters(), lr=learning_rate, **kwargs
    227         )
    228 

TypeError: __init__() got an unexpected keyword argument 'train_with_test'
````
**Second question**:
What is the right way to test a model on a new dataset? I defined a new corpus for testing data as follows:
````
corpus_testing: Corpus = ColumnCorpus(data_folder, columns, test_file = 'test_MOD.txt')
````
Then I use my trained model on the test part of testing corpus to get the predictions:
````
# Evaluation on test part of the corpus (806 sentences)
result_test, score = model_MOD.evaluate(corpus_testing.test, mini_batch_size=1, out_path=f"predictions_test.txt")

print(result_test.detailed_results)
````
Is it a valid way? or there is another better ways?

Thanks in advance!

**Comment by alejosierra** [comment]
I am having the same issue with train_with_test, Is there any other way of using my full corpora to train a model?

**Comment by alanakbik** [comment]
Could you try updating Flair to 0.8?

**Comment by alejosierra** [comment]
The error with test_with_train dissapeared after upgrading to 0.8. The trainer console output is not showing the parameter though, but I guess it is indeed using the test dataset because at the end it didn't perform any testing.

trainer:
`
trainer.train(base_path,
                  learning_rate=0.01,
                  mini_batch_size=50,
                  max_epochs=1,
                  embeddings_storage_mode='gpu',
                  num_workers=4,
                  train_with_dev=True,
                  train_with_test=True,
                  checkpoint=True
                )
`

`
2021-03-08 11:11:40,542 ----------------------------------------------------------------------------------------------------
2021-03-08 11:11:40,547 Corpus: "MultiCorpus: 1304 train + 145 dev + 161 test sentences
 - ColumnCorpus Corpus: 1304 train + 145 dev + 161 test sentences"
2021-03-08 11:11:40,548 ----------------------------------------------------------------------------------------------------
2021-03-08 11:11:40,549 Parameters:
2021-03-08 11:11:40,549  - learning_rate: "0.01"
2021-03-08 11:11:40,550  - mini_batch_size: "50"
2021-03-08 11:11:40,551  - patience: "3"
2021-03-08 11:11:40,553  - anneal_factor: "0.5"
2021-03-08 11:11:40,553  - max_epochs: "1"
2021-03-08 11:11:40,553  - shuffle: "True"
2021-03-08 11:11:40,554  - train_with_dev: "True"
2021-03-08 11:11:40,554  - batch_growth_annealing: "False"
2021-03-08 11:11:40,554 ----------------------------------------------------------------------------------------------------
2021-03-08 11:11:40,555 Model training base path: "..\results\results\flair-ner\train_test_example_20210308111134"
2021-03-08 11:11:40,555 ----------------------------------------------------------------------------------------------------
2021-03-08 11:11:40,556 Device: cuda:0
2021-03-08 11:11:40,556 ----------------------------------------------------------------------------------------------------
2021-03-08 11:11:40,556 Embeddings storage mode: gpu
2021-03-08 11:11:40,558 ----------------------------------------------------------------------------------------------------
2021-03-08 11:11:42,868 epoch 1 - iter 3/33 - loss 109.78243256 - samples/sec: 64.99 - lr: 0.010000
2021-03-08 11:11:45,442 epoch 1 - iter 6/33 - loss 103.07271703 - samples/sec: 58.28 - lr: 0.010000
2021-03-08 11:11:48,634 epoch 1 - iter 9/33 - loss 104.03900909 - samples/sec: 46.99 - lr: 0.010000
2021-03-08 11:11:51,015 epoch 1 - iter 12/33 - loss 99.56274287 - samples/sec: 62.99 - lr: 0.010000
2021-03-08 11:11:53,826 epoch 1 - iter 15/33 - loss 95.49834595 - samples/sec: 53.38 - lr: 0.010000
2021-03-08 11:11:55,839 epoch 1 - iter 18/33 - loss 90.68513277 - samples/sec: 74.53 - lr: 0.010000
2021-03-08 11:11:58,019 epoch 1 - iter 21/33 - loss 86.02749961 - samples/sec: 68.84 - lr: 0.010000
2021-03-08 11:12:00,111 epoch 1 - iter 24/33 - loss 81.88932037 - samples/sec: 71.71 - lr: 0.010000
2021-03-08 11:12:03,344 epoch 1 - iter 27/33 - loss 79.21509001 - samples/sec: 46.40 - lr: 0.010000
2021-03-08 11:12:05,439 epoch 1 - iter 30/33 - loss 76.38486697 - samples/sec: 71.66 - lr: 0.010000
2021-03-08 11:12:07,306 epoch 1 - iter 33/33 - loss 73.95241315 - samples/sec: 80.36 - lr: 0.010000
2021-03-08 11:12:07,306 ----------------------------------------------------------------------------------------------------
2021-03-08 11:12:07,307 EPOCH 1 done: loss 73.9524 - lr 0.0100000
2021-03-08 11:12:07,315 BAD EPOCHS (no improvement): 0
2021-03-08 11:12:25,315 Test data not provided setting final score to 0
2021-03-08 11:12:25,661 ----------------------------------------------------------------------------------------------------
`
