### ISSUE TITLE
Error when using 'sentiment': ModuleNotFoundError: No module named 'transformers.modeling_distilbert'

### ISSUE THREAD

**Issue by ftrias** [flairNLP/flair#2109]
I have a clean install (Feb 16) of Flair. Using this code directly from  the tutorial:

```python
from flair.models import TextClassifier
classifier = TextClassifier.load('sentiment')
sentence = Sentence("enormously entertaining for moviegoers of any age .")
classifier.predict(sentence)
print(sentence)
```

I get the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-bf2c8f4f80e8> in <module>
      2 # import transformers.models.distilbert
      3 
----> 4 classifier = TextClassifier.load('sentiment')
      5 
      6 # predict for example sentence

~/opt/anaconda3/envs/thesis/lib/python3.9/site-packages/flair/nn.py in load(cls, model)
     86             # see https://github.com/zalandoresearch/flair/issues/351
     87             f = file_utils.load_big_file(str(model_file))
---> 88             state = torch.load(f, map_location='cpu')
     89 
     90         model = cls._init_model_with_state_dict(state)

~/opt/anaconda3/envs/thesis/lib/python3.9/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    592                     opened_file.seek(orig_position)
    593                     return torch.jit.load(opened_file)
--> 594                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    595         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    596 

~/opt/anaconda3/envs/thesis/lib/python3.9/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
    851     unpickler = pickle_module.Unpickler(data_file, **pickle_load_args)
    852     unpickler.persistent_load = persistent_load
--> 853     result = unpickler.load()
    854 
    855     torch._utils._validate_loaded_sparse_tensors()

ModuleNotFoundError: No module named 'transformers.modeling_distilbert'
```

Using MacOS 11.2.1 with Anaconda Python 3.9.1

It appears that the `transfomers` module was reorganized on  16 Nov 2020 #8580 (https://github.com/huggingface/transformers/commit/c89bdfbe720bc8f41c7dc6db5473a2cb0955f224#diff-550edeb1fa88e111752fd13ba725609f25858d5729dfe10b9773918bc1e974a1) but the downloaded model pickle files use the previous module organization.

I tried installing the previous version of transformers (3.5.0) but it fails with a dependency error:

```
$ pip install -Iv transformers==3.5.0
...
ERROR: Could not find a version that satisfies the requirement sentencepiece==0.1.91 (from transformers)
ERROR: No matching distribution found for sentencepiece==0.1.91
```

Installing 3.4.0 of `transformers` fails when compiling `tokenizers` with `rustc`. Installing 3.3.0 of `transformers` succeeds in compiling, but executing the code at the top generates:

```
ImportError: cannot import name '_BaseLazyModule' from 'transformers.file_utils' (/Users/ftrias/opt/anaconda3/envs/thesis/lib/python3.9/site-packages/transformers/file_utils.py)
```

**Comment by Precel2000** [comment]
You might need to downgrade your python to be able to run it. For me it worked with python 3.7.6

**Comment by alanakbik** [comment]
This issue should be fixed with the latest release. Could you try again?

**Comment by GladiatorX** [comment]
The error still persist, even on upgrading to flair==0.8.0.post1

**Comment by ashokxnarang** [comment]
Got a similar error while testing keyphrase Sequence Tagger:. I am on Flair 0.8 and the latest transformers version.

Ashok

#---------------------------------------------------------------------#
  File "test_keyphrase_tagger.py", line 23, in <module>
    main()
  File "test_keyphrase_tagger.py", line 10, in main
    tagger = SequenceTagger.load('keyphrase')
  File "C:\Python37\lib\site-packages\flair\nn.py", line 88, in load
    state = torch.load(f, map_location='cpu')
  File "C:\Python37\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Python37\lib\site-packages\torch\serialization.py", line 774, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'transformers.modeling_bert'
#---------------------------------------------------------------------#

**Comment by mrSaraf25** [comment]
Hello @alanakbik,
How do I handle this? please help

Thanks!

**Comment by muellerzr** [comment]
Looks like post transformers 3.5.1 this was moved to transformers/models/distilbert/modeling_distilbert. So far the only solution for me is to downgrade transformers (which isn't ideal as they're now on 4.5)

**Comment by LakshmiPanguluri** [comment]
having the same issue on flair 0.8.0.post1 and transformers 4.9.  Any solutions?
