### ISSUE TITLE
Model trained on version<=0.5.0 is not compatible on 0.5.1

### ISSUE THREAD

**Issue by ciaochiaociao** [flairNLP/flair#1801]
As mentioned in the title, I have trained some models on version <=0.5.0. When I upgrade to 0.5.1, the trained model is no longer available for doing inference.

I think the problem is in your latest release, you refactored the StackedEmbedding, and it does not have the `get_names` method in the old version. So in the `tagger.predict()` method, the following erred. 
```
class SequenceTagger:
    def predict(self):
        ...
        self.embeddings.get_names(...)  # AttributeError: StackedEmbedding has no get_names attribute in version<=0.5.0
```

 I know I can downgrade to 0.5.0 or re-train my model on 0.5.1, but I have some codes relying on some good features you provide in 0.5.1 and training process is a bit expensive in my case. Maybe you can consider a minimal compatibility of models between different versions in the next release. 

Regards

**Comment by alanakbik** [comment]
Hello @ciaochiaociao - I believe the old models should still work. Many of the models we ship in Flair were trained in 0.4 - like the standard 'ner' model we always use in the example. This still works in 0.5.1, so maybe there is another issue?

**Comment by ciaochiaociao** [comment]
Thanks for your prompt reply! Maybe there is another issue. I will post more information, code and the exception message later.

**Comment by ciaochiaociao** [comment]
I have checked the current version of flair is 0.5.1 by checking `flair.__version__`.

My Code to load a model that was trained on some versions before 0.5.1 (Sorry I forgot which one I used before after upgrading to 0.5.1. )
```
ner = SequenceTagger.load('models/flair_on_conll_lr0.1_b32_e150_wo_dev/best-model.pt')
s = Sentence('Donald Trump is nominated by NRC.')
ner.predict(s)
```


The following is the error message.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-12-b803dff4615a> in <module>
----> 1 ner.predict(s)

~/.local/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py in predict(self, sentences, mini_batch_size, all_tag_prob, verbose, label_name, return_loss, embedding_storage_mode)
    364                     continue
    365 
--> 366                 feature = self.forward(batch)
    367 
    368                 if return_loss:

~/.local/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py in forward(self, sentences)
    604         self.embeddings.embed(sentences)
    605 
--> 606         names = self.embeddings.get_names()
    607 
    608         lengths: List[int] = [len(sentence.tokens) for sentence in sentences]

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    589                 return modules[name]
    590         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 591             type(self).__name__, name))
    592 
    593     def __setattr__(self, name, value):

AttributeError: 'StackedEmbeddings' object has no attribute 'get_names'
```

What I have done:
I also check the default ner model you provided: `~/.flair/models/en-ner-conll03-v0.4.pt` by using
```
default_ner = SequenceTagger.load('ner')  # load default path
s = Sentence('Donald Trump is nominated by NRC.')
default_ner.predict(s)
```
And it works instead!!

So I further check if the model I trained before has the `StackedEmbeddings.get_names` method by 

```
ner.embeddings.get_names
```

And it shows it indeed does not have that method
```
AttributeError                            Traceback (most recent call last)
<ipython-input-17-11cca5fcecd5> in <module>
----> 1 ner.embeddings.get_names

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    589                 return modules[name]
    590         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 591             type(self).__name__, name))
    592 
    593     def __setattr__(self, name, value):

AttributeError: 'StackedEmbeddings' object has no attribute 'get_names'
```

I suspect the previous model I trained and saved might use a version of flair that does have `StackedEmbeddings` without `get_names` method such as versions before this [commit](https://github.com/flairNLP/flair/commit/a6e13e6fef8ba7eab88cb96a4f0ec05e7787f95e)

(By the way, is there any way that I can check the version of the flair module I trained my model with?)

**Comment by ciaochiaociao** [comment]
Update: After downgrading to flair==0.5.0, it did solve the issue. But it seems that there is indeed some incompatibility between 0.5.0 and 0.5.1
