### ISSUE TITLE
AttributeError: 'ELMoEmbeddings' object has no attribute 'embedding_mode_fn'

### ISSUE THREAD

**Issue by yzhaoinuw** [flairNLP/flair#1634]
Hi Flair developers, thank you for releasing version 0.5 of flair. I am very excited and wasted no time trying it. I upgraded it today to release 0.5 from release 0.45. Then I went ahead to run an NER module I made afew days ago to see if I need to make changes to my module because of the new flair release. My NER module uses the flair sequence tagger and the ELMo embeddings. But now I encounter the following error message:

```
  File "/home/Desktop/name_parser.py", line 44, in parse_name
    self.model.predict(name,all_tag_prob=True)

  File "/home/anaconda3/envs/nlp/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 372, in predict
    feature: torch.Tensor = self.forward(batch)

  File "/home/anaconda3/envs/nlp/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 513, in forward
    self.embeddings.embed(sentences)

  File "/home/anaconda3/envs/nlp/lib/python3.7/site-packages/flair/embeddings/base.py", line 59, in embed
    self._add_embeddings_internal(sentences)

  File "/home/anaconda3/envs/nlp/lib/python3.7/site-packages/flair/embeddings/token.py", line 1594, in _add_embeddings_internal
    word_embedding = self.embedding_mode_fn(elmo_embedding_layers)

  File "/home/anaconda3/envs/nlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))

AttributeError: 'ELMoEmbeddings' object has no attribute 'embedding_mode_fn'
```

One code in my module loads a NER model I trained, which used the ELMo emneddings. Then, I use the loaded model to predict NER tags. My module was working well with flair 0.45. All that changed was was that I upgraded flair to 0.5. I tried to look in to ELMoEmbeddings class in [token.py](https://github.com/flairNLP/flair/blob/083eb114505ede0ea3070317a5a08d13fc71891b/flair/embeddings/token.py) and found from line 1543 to 1548 where it is defined as follows

```
 if embedding_mode == "all":
        self.embedding_mode_fn = lambda x: torch.cat(x, 0)
elif embedding_mode == "top":
        self.embedding_mode_fn = lambda x: x[-1]
elif embedding_mode == "average":
        self.embedding_mode_fn = lambda x: torch.mean(torch.stack(x), 0)
```

I don't remember specifying the mode for ELMo when I trained the NER model. This is new feature in this release, right? Do I have need to retrain the model with ELMo and specify the mode? Is there a quicker fix?

Thank you!

**Comment by yzhaoinuw** [comment]
I found a quick fix. Add a line after the line where the model is loaded, to specify self.embedding_mode_fn of the ELMoEmbeddings class :
```
model = SequenceTagger.load(path/to/model)
model.embeddings.embedding_mode_fn = lambda x: torch.cat(x, 0)
```
It seems that ```lambda x: torch.cat(x, 0)```, which corresponds to all layer of ELMo being used, is the only function that works if loading model that uses ELMo embeddings from releases previous to 0.5. Maybe this could be a fix to make the current release more compatible with earlier model that used ELMo?

**Comment by alanakbik** [comment]
Thanks! Yes - thats a good point, we should add this!

**Comment by alanakbik** [comment]
PR merged, thanks for your help!
