### ISSUE TITLE
ImportError: cannot import name 'TransformerEncoderLayer

### ISSUE THREAD

**Issue by JoyHuYY1412** [flairNLP/flair#1236]
My pytorch is 1.1.0 and python is 3.6.8.

**Comment by JoyHuYY1412** [comment]
I switch the version to 0.4.3 and the question is not reported.

**Comment by NDTanja** [comment]
I also get the ImportError with flair 0.4.4. With flair 0.4.3 everything works fine.

**Comment by yosipk** [comment]
Could you, please, upgrade PyTorch to 1.2.0 (`pip install torch==1.2.0`) since AFAIK that's the first version that has `torch.nn.TransformerEncoderLayer`. If that works, we'll just have to bump the PyTorch version in `requirements.txt`.

**Comment by NDTanja** [comment]
I updated PyTorch to the latest version (1.3.0) but unfortunately, I still get the ImportError. I am using Python 3.8.0

**Comment by robertodias** [comment]
Same thing to me, I am using AWS Sagemaker notebooks.
this seams to be a flair 0.44 issue, because it all work fine when we force it back to 0.43

`!pip install flair==0.4.3 `

**Comment by alanakbik** [comment]
@robertodias have you tried setting torch to `1.2.0`?

**Comment by Happyflytoyou** [comment]
Python 3.7 + Pytorch 1.2.0 + flair 0.4.4 works for me

**Comment by 99991** [comment]
Curiously, I had the same issue with `torch==1.2.0` and `flair==0.4.4` but it works with `torch==1.3.0`.

**Comment by cooleel** [comment]
torch==1.2.0 and flair==0.4.4 work for me.

**Comment by LLh-lihan** [comment]
same problem here. Pytorch 1.10.2 and python 3.6
